### ISSUE TITLE
Replace Cython OpenMP parallelism with Python multiprocessing or joblib

### ISSUE THREAD

**Issue by leouieda** [fatiando/fatiando#165]
PR #106 introduced a cheap (and rather dumb) form of parallelism for `fatiando.gravmag` forward modeling Cython functions. It's good because it is just one line change in Cython, it's automatic, and gives moderate speedups. It's bad because we get a lot of errors for building Fatiando under Windows (#159 and #164).

A better alternative is to remove it (and get rid of extra Windows dependencies) in favor of a higher level form of parallelism. We could use [multiprocessing](https://docs.python.org/2/library/multiprocessing.html) or [joblib](https://pythonhosted.org/joblib/index.html) and move the parallelism into the Python part of the code (`fatiando/gravmap/prism.py`, etc). There would be no extra compile dependencies and pure Python code only. A drawback is that it would no longer be automatic.

The automatic  part came in handy for sensitivity matrix building (like in `fatiando.gravmag.eqlayer.PELGravity`). But we can replace it by building the matrix in parallel using multiprocessing. 

The forward modeling functions should take a `jobs` argument to say how many processes to use. If `None`, just run it serial. This would create a lot of duplicate code but [we can worry about that later](http://gael-varoquaux.info/programming/software-design-for-maintainability.html).

**Comment by eusoubrasileiro** [comment]
@leouieda master I don't know if I get it. 
>A drawback is that it would no longer be automatic.
I did not get the whole idea but I like to rely on python alone using multiprocessing and joblib

**Comment by leouieda** [comment]
The idea was that compiling OpenMP Cython code in Windows was a nightmare :wink:

But this should already be closed. Adding a bit of parallelism will be done in #289
