### ISSUE TITLE
Merge gravmag.fourier and gravmag.transform

### ISSUE THREAD

**Issue by leouieda** [fatiando/fatiando#171]
The `fatiando.gravmag.fourier` module basically implements field transformations in the frequency domain. It doesn't really do the FFT, just uses it. A better fit for the functions there would be the `fatiando.gravmag.transform` module for field transformations.

I propose to remove the `fourier` module and move its functions to `transform`. The tests and scripts would have to be updated to import from the new location.

**Comment by mtb-za** [comment]
Are you including the `fatiando.gravmag.fourier.derivx` / `fatiando.gravmag.fourier.derivy` / `fatiando.gravmag.fourier.derivz` set in this as well? In `fatiando.gravmag.fourier` they are listed as derivatives rather than transformations, which currently only includes `fatiando.gravmag.fourier.ansig`, which has been flagged for a name change in https://github.com/fatiando/fatiando/issues/154. It might be worth doing both changes at once.

**Comment by leouieda** [comment]
@mtb-za yes, I'm including all of `fourier` on this. I guess you could think of the derivatives as a kind of filter or transformation of the original data. I just thought that it might make more sense to have all of that in the same module. And one with a name people would actually look for when searching for that kind of thing.

We could certainly do this with #154 in one go. Wouldn't be much trouble, except for migrating the current cookbook recipes.

**Comment by mtb-za** [comment]
I seem to have missed this, but I can move the stuff over (hopefully some time this week). I can also look at the recipes at the same time.

**Comment by leouieda** [comment]
That's great, thanks! Please have a look at the [developer docs](http://fatiando.github.io/develop.html) if you haven't already. Let me know if you need any help.

**Comment by mtb-za** [comment]
I have made this change. Unless I did something wrong, it seems to work.

https://github.com/mtb-za/fatiando/tree/gravmag_merge

Is there anything that I need to do to update the docs?

**Comment by leouieda** [comment]
@mtb-za thanks for taking the time to do this! 

I had a brief look at the code and things seem to checkout. Could you [open a pull request](https://help.github.com/articles/creating-a-pull-request/) for this? That way I can view all the changes, leave comments, and [TravisCI will automatically run our tests](https://travis-ci.org/fatiando/fatiando/). I have a few comments about the `tdh` function.

There are a few things that you'll need to change in the docs. I'll give you better instructions in the pull request (PR in github lingo).

**Comment by leouieda** [comment]
Fixed by #186
