### ISSUE TITLE
Setup continuous integration for Windows 

### ISSUE THREAD

**Issue by leouieda** [fatiando/fatiando#180]
The TravisCI service runs our tests under a Linux (Ubuntu) system. However, most of our problems and bug reports come from Windows. We need to setup a Windows CI service to run the tests on Windows (32 and 64bit) to make sure everything works before shipping a new feature.

A good option is https://ci.appveyor.com/login

**Comment by eusoubrasileiro** [comment]
@leouieda so many PR and feature requests wow.. fatiando is really growing recently.

this one is also a nice one.

**Comment by leouieda** [comment]
This https://github.com/astropy/ci-helpers has all the code we need to setup appveyor.
