### ISSUE TITLE
Pass kwargs to along to matplotlib functions in fatiando.vis.mpl

### ISSUE THREAD

**Issue by santisoler** [fatiando/fatiando#193]
While using the mpl module I've noticed that I can't put **kwargs as inputs of some functions. For example, if I want to put a transparency in a contourf with pyplot I just add "alpha=alpha_value" and then I got it. But with mpl I cannot do it, so it forces me to go back to pyplot.

I've started thinking to change it, but when I realised that it is a very easy job I wondered: Is there any reason because it wasn't applied in the first time? If there's none, I would be happy to apply those modifications, initially to the functions:
    - contour
    - contourf
    - pcolor
    - points
    - paths
    - square
    - polygon

Greetings!

**Comment by leouieda** [comment]
@santis19 the main reason for not passing along kwargs is that I didn't think of it at the time :-1: 

I completely agree with you that this should be norm for all functions that we have overwritten  in `vis.mpl`. It wouldn't be much trouble I guess to just pass the extra arguments along. You're welcome to start this if you'd like. I'd be very thankful :+1:

This raises a bigger issue that I've had on my mind about the `vis` package. There are several things that are bugging me about it. I'll open a new issue to discuss this but it is more longterm plans and doesn't impact this issue.
