### ISSUE TITLE
Build conda packages and wheels

### ISSUE THREAD

**Issue by leouieda** [fatiando/fatiando#197]
Installing is the greatest barrier to entry that we have. Windows users usually have a terrible time getting Fatiando compiled. This is the reason why we removed OpenMP support (#177). 

## A better way

I can see two options for making this easier:

1. Get rid of all compiled modules. We could potentially replace them with numba implementations (#169 and #175). This can be a lot of work and we would loose the advantage if we ever wrap some C or Fortran code.
2. Distribute pre-compiled binaries of Fatiando for all OSs (Windows, Linux, OSX) and architectures (32 and 64bit). The compiled packages can be [conda packages](http://conda.pydata.org/) and/or [Python wheels](http://pythonwheels.com/), preferably both. This adds extra work for the developers when making a new release but can potentially be automated with TravisCI and Appveyor.

I tend to prefer option 2 because it won't limit the development so much. I liked writing the tesseroid code in numba and found it much easier than Cython. So we can strive for a mixture of the two and try to avoid creating new compiled code by using numba.

**Comment by leouieda** [comment]
This issue is a broader case of #181

**Comment by leouieda** [comment]
Resolving #180 (CI for Windows) will help with this.

**Comment by eusoubrasileiro** [comment]
@leouieda I tend to go with 2. The less job the better hehe I want to focus more on new stuff

**Comment by leouieda** [comment]
Closed because this is solved with conda-forge: https://github.com/conda-forge/fatiando-feedstock
