### ISSUE TITLE
Increment the fatiando.datasets module and include data with software

### ISSUE THREAD

**Issue by leouieda** [fatiando/fatiando#202]
The `fatiando.datasets` module started as a way to load some standard data that we can use in examples (cookbook, tutorials, etc). In its current form, it only downloads the CRUST2.0 model and a sample Bouguer anomaly that I stored in [a gist](https://gist.github.com/leouieda/6023922). Both of these have to be downloaded every time, which is not ideal.

This point has been touched before in #78 and #49 
## Makeover

The `datasets` module ideally would have functions to load the data that we ship with Fatiando. This way the user doesn't need to know where the data files have been stored and we have a reliable way of including them in the recipes.

Sample data sets would have to be small and freely (legally) available. They can be included in a `data` directory, either in the `fatiando` package or in the repository base. Since they are small, it won't be a problem checking them into version control if we don't keep changing them all the time. They should be representative of each method and can be synthetic data.

We need to compile a list of at least one data set for each method that we support (mostly gravity, magnetic, and seismic reflection). Each data set will have a function in `datasets` that will load the data from the local copy. There can be some extra datasets that can be downloaded (as suggested in #78) but the main ones used in the Cookbook should be included for offline usage.

**Comment by mtb-za** [comment]
This sounds like a good plan.

**Comment by eusoubrasileiro** [comment]
and a nice plan.

**Comment by leouieda** [comment]
:+1: 

@eusoubrasileiro, @mtb-za. @hbueno it would be great to get some suggestions of possible data sets. 

For gravity, we can download from [ICGEM](http://icgem.gfz-potsdam.de/ICGEM/). They are based on spherical harmonic models so we can get data from anywhere we want, even global.

Any ideas for magnetic and seismic?

**Comment by mtb-za** [comment]
I think I saw something about there being some seismic data sets from Norway and such that might work. Maybe @kwinkunks would know of some?

No idea for mag data though.

**Comment by eusoubrasileiro** [comment]
also there is the well known synthetic marmousi data (pre-stack gathers) set that madagascar makes available and I used for the obspy seis vis cookbook. It is small and simple, for our purposes I think that might fit very well.

**Comment by leouieda** [comment]
Just remembered that we started a wiki page for this: https://github.com/fatiando/fatiando/wiki/Open-geophysical-data-sets

There is also the SEG Wiki page for open data: http://wiki.seg.org/wiki/Open_data

**Comment by eusoubrasileiro** [comment]
@leouieda nice page good referenceI will take a better look, we can surely use any of those also they seem to be more recent

**Comment by leouieda** [comment]
This is done now in #355. For now, only a gravity dataset is included but adding new ones is easier now because we have somewhere to start. It would be good to have more data in here. For example, having a single CMP gather that we can load would go really nicely with #352
