### ISSUE TITLE
Clean up the Cookbook

### ISSUE THREAD

**Issue by leouieda** [fatiando/fatiando#211]
The cookbook is a bit too large right now. It can be very difficult to find a recipe that does what you want. We need to simplify the recipes and greatly reduce their number. There are a bunch of them that do almost the same thing but with different parameters (using different regularization or variants of a method).  These can be unified into a single recipe that shows both options side by side.

**Comment by eusoubrasileiro** [comment]
what about instead of removing them we make a better search mechanism? if their description are good more will mean more help for the end user

**Comment by leouieda** [comment]
But it doesn't help if you don't know what you're looking for. That is the
case if you're new to the software and just want to have a look at what is
available.

**Comment by eusoubrasileiro** [comment]
I think that shortening the number of recipes is not the way to go.  I think that another page with a short introduction and also grouping the cookbooks would help much more the newcomer. The guy must at least know what he wants to do on the general scope that fatiando offers.

**Comment by leouieda** [comment]
:+1: OK, you have a good point. Maybe not remove things, but group the redundant recipes together? 

Also, I'm working on having the tutorials page set up. I got an initial prototype of turning an IPython notebook into a sphinx page (copied from [seaborn](https://github.com/mwaskom/seaborn)). 

So we'll have the tutorials and the cookbook could be more of a gallery. For that, I'd like to have the gallery sorted by plots, like in matplotlib. But I can't do that with recipes that use Mayavi or generate more than on plot. So what I'd like to have each recipe make a single matplotlib plot (can be as complex as you like, with many subplots). The 3D examples can be left to an IPython notebook just for Mayavi plotting (the figures can be embed using `IPython.display.Image`). Also, all the tutorials could use Mayavi as much as they want, just not the recipes. 

What do you think?

**Comment by eusoubrasileiro** [comment]
Exactly! 
Turning an IPython notebook into a sphinx page, that sounds cool!

About the gallery awesome! I like that way of thinking.

But I am thinking on how much re-work you will have especially to split those recipes that have 3D plots from those that dont. From now on I like the idea just worried about re-factoring stuff that dont fit. Was thinking something more simpler like just a tree of topics, like a help page by topics. 
Just throwing some thoughts ...

**Comment by eusoubrasileiro** [comment]
btw seaborn is amazing

**Comment by leouieda** [comment]
Yes, it will be a lot of work, but not particularly difficult work. That's
why I marked this as low hanging fruit. We don't have to do this in a
hurry, but we should encourage new recipes to already fit into this new
format. The tree idea would be a good middle ground but I think it won't be
much easier than fixing the recipes. So maybe it's not worth the effort of
we'll get rid of it later anyway.

Another cool thing about the gallery is that it adds images to our page.
There are no plots for Fatiando anywhere. So you can't tell at a glance
what the package does. It would be nice to have some cool images in the
front page to catch the eye.

**Comment by eusoubrasileiro** [comment]
Ok than. Then lets go for it :+1:

**Comment by leouieda** [comment]
I'll be waiting for your PR then :coffee:

**Comment by eusoubrasileiro** [comment]
heheh ok sounds good I will find some time after the 13th bid round to learn sphinx. Also fix the recipes to a single plot.

**Comment by leouieda** [comment]
Don't worry about it! I know you're busy with work and personal things.

**Comment by leouieda** [comment]
NOTE: Take a look at https://github.com/sphinx-gallery/sphinx-gallery to generate a gallery (like matplotlib) from the examples in the cookbook.

**Comment by eusoubrasileiro** [comment]
it will be cool being like matplotlib, nice!

**Comment by leouieda** [comment]
Closing because the Cookbook is already being phased out in favor of the Gallery.
