### ISSUE TITLE
Minor Sphinx install update needed in Dev guide

### ISSUE THREAD

**Issue by drandykass** [fatiando/fatiando#236]
I recently wiped and reinstalled MacOS and was able to follow the install instructions for Fatiando and the development guide exactly.  There's a small issue in the installation of Sphinx_bootstrap_theme, at least in OS X.  

Currently, an earlier version is installed with Anaconda.  When following the dev guide, it reports that the dependency is already met; however all equations are shown as 
[*Math Processing Error*].

To clear this, one needs to run
pip install sphinx_bootstrap_theme --upgrade

which results in the proper output.

My system:
Fatiando: 0.3-327-ge1bf5d9 (my own forked copy)
Anaconda 2.4.0 (python 2.7.10)
Sphinx 1.3.1
Sphinx_bootstrap_theme *working* version 0.4.5
OS X El Capitan 10.11.1

**Comment by leouieda** [comment]
@drandykass thanks for pointing that out. I have sphinx_bootstrap_theme 0.4.5 on my personal computer as well. 

I just noticed that the [developer docs](http://www.fatiando.org/develop.html#setting-up) says to run `pip install -r test/requirements-pip.txt`. That should have installed version 0.4.5 of the theme as stated in the requirements file. Did you run this command?

Either way, the instructions in http://www.fatiando.org/develop.html#setting-up should be enough that the extra `pip install` in http://www.fatiando.org/develop.html#documentation should not be needed and should be removed from the docs.

**Comment by drandykass** [comment]
I think I followed that but I can't remember explicitly.  I tried to follow
the install and dev instructions as closely as I could since it was a fresh
new install.  Can't guarantee that though.

On Wed, Nov 25, 2015 at 2:13 PM, Leonardo Uieda <notifications@github.com>
wrote:

> @drandykass <https://github.com/drandykass> thanks for pointing that out.
> I have sphinx_bootstrap_theme 0.4.5 on my personal computer as well.
>
> I just noticed that the developer docs
> <http://www.fatiando.org/develop.html#setting-up> says to run pip install
> -r test/requirements-pip.txt. That should have installed version 0.4.5 of
> the theme as stated in the requirements file. Did you run this command?
>
> Either way, the instructions in
> http://www.fatiando.org/develop.html#setting-up should be enough that the
> extra pip install in http://www.fatiando.org/develop.html#documentation
> should not be needed and should be removed from the docs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fatiando/fatiando/issues/236#issuecomment-159732722>.
>



-- 
------------------------------------------------------------------------------------
Dum inter homines sumus, colamus humanitatem.
------------------------------------------------------------------------------------

**Comment by leouieda** [comment]
That's OK. I'll update the docs to say to explicitly install 0.4.5.
