### ISSUE TITLE
Dev Page - Broken link to testing

### ISSUE THREAD

**Issue by drandykass** [fatiando/fatiando#240]
Software Caprentry has removed their lessons on testing for a bizarre reason.  As a consequence, the link provided under the Testing section on the dev pages is now broken (despite it STILL being the top google result if you search 'testing' on the software-carpentry site).

More information:
http://software-carpentry.org/blog/2014/10/why-we-dont-teach-testing.html

I do not have an alternative suggestion for a tutorial on building tests yet, though I will be searching; I need to build tests for new code now.

**Comment by leouieda** [comment]
Seems that all Software Carpentry links are broken. They must have changed their page layout. Might be better to link only to http://software-carpentry.org/ and write the name of the appropriate lesson.

**Comment by leouieda** [comment]
Just to be clear for anyone interested, these changes need to happen in `doc/develop.rst`.

**Comment by drandykass** [comment]
Roger.  Would it be easier if I catch these small things to branch and pull
request it myself?

On Thu, Dec 3, 2015 at 10:13 AM, Leonardo Uieda <notifications@github.com>
wrote:

> Just to be clear for anyone interested, these changes need to happen in
> doc/develop.rst.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fatiando/fatiando/issues/240#issuecomment-161719619>.
>



-- 
------------------------------------------------------------------------------------
Dum inter homines sumus, colamus humanitatem.
------------------------------------------------------------------------------------

**Comment by leouieda** [comment]
Sure, that would be great! Thanks
