### ISSUE TITLE
make test error in gravmag.tensor.center_of_mass

### ISSUE THREAD

**Issue by drandykass** [fatiando/fatiando#241]
There is a small error which results in a failed make test.  There appears to just be an extra space in the returned array which results in the arrays not being treated as equal.

======================================================================
FAIL: Doctest: fatiando.gravmag.tensor.center_of_mass
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mkass/anaconda/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for fatiando.gravmag.tensor.center_of_mass
  File "/Users/mkass/Projects/fatiando/fatiando/gravmag/tensor.py", line 140, in center_of_mass

----------------------------------------------------------------------
File "/Users/mkass/Projects/fatiando/fatiando/gravmag/tensor.py", line 189, in fatiando.gravmag.tensor.center_of_mass
Failed example:
    cm
Expected:
    array([-100.,  20., 100.])
Got:
    array([-100.,   20.,  100.])

----------------------------------------------------------------------

Fatiando version: 
>>> fatiando.__version__
'0.3-329-gc477695-dirty'

**Comment by leouieda** [comment]
@drandykass this test is always failing depending on the computer. It shouldn't use the raw array as output like that. It would be much better to print the values using a given precision. That way the tests wouldn't break all the time. This is minor and it doesn't fail on TravisCI.

**Comment by leouieda** [comment]
@drandykass this is being fixed by #242 if you want to take a look. There isn't much to do so I'll merge the PR as soon as the tests pass.
