### ISSUE TITLE
Make fatiando.mesher into a package

### ISSUE THREAD

**Issue by leouieda** [fatiando/fatiando#278]
The same reasoning as in #277.  `fatiando.mesher` is getting too big. Would be better to make it a package, separate the classes into modules, and import the public classes in `__init__.py`.

Suggested structure:
- `base`: for base classes (not loaded in `__init__.py`) like `GeometricElement` etc.
- `geometry`: for primitive types, like `Prism`, `Sphere`, etc
- `mesh`: for 2D and 3D meshes, like `PrismMesh` and `SquareMesh`
- `points`: for `PointGrid` and other up-coming classes (`PointScatter`)
- `relief`: for `PrismRelief` and future `TesseroidRelief`

**Comment by PiotrKurnik** [comment]
I have started looking into this.

**Comment by leouieda** [comment]
@PiotrKurnik Thanks! Let me know when you have something.

**Comment by rowanc1** [comment]
Similar issue here:
simpeg/simpeg#360

It would be interesting to perhaps collaborate on some of this. Our `discretize` package would be pretty influenced by PDE stuff, but I think that there would be a lot of overlap with the geometries etc. that you are using in your various problems.

**Comment by PiotrKurnik** [comment]
Interesting. @leouieda, any thoughts on that?

**Comment by leouieda** [comment]
@rowanc1 I've been giving this some thought. It'd be great to have something we all use together. I've been thinking of how to loosen the coupling between the calculation and inversion functions in Fatiando and the meshing part so that it could be stripped out. 

I like the meshing in simpeg. You have mostly meshes (as opposed to geometric objects like polyhedra, spheres) right? If we can make that work with having both, then I'm in. 

It would be a good home for plotting functions of these objects as well. I like how you use mostly cross-sections. They are a better representation of the results. But it wouldn't work for our `PolygonalPrism`s or `Sphere`s.

**Comment by rowanc1** [comment]
Yes, we mostly just have computational meshes, currently 4 types:

![image](https://cloud.githubusercontent.com/assets/913249/20465861/a84cb2a6-af24-11e6-83f2-d97ac2ff37b5.png)

And cylindrical.

These are programmed up for 1D-4D and give you the basic operators (Div Grad Curl), averaging, and interpolation. There is simple plotting; this needs a bit of love, however.

We don't have primitive geometric types, and I guess I would like to know more about how you use them. I don't think there would be any issue to including these? We would just have to get the namespace right (not very hard...?).

We were thinking about splitting it off into a `discretize` package. For ways to discretize the earth. :)

It would be great to work with you on this. If you are game, this would be a good catalyst to start this project off and pull the pieces out of `SimPEG`.

**Comment by leouieda** [comment]
I'm in!

In Fatiando we have mostly 3D primitives: `Prism`, `PolygonalPrism`, `Sphere`, and `Tesseroid`. Then there are collections of these primitives which are our meshes: `PrismMesh`, `TesseroidMesh`, `PointGrid`, etc. The collections are basically iterators of primitives and have a few methods for manipulating them. This is an old module in Fatiando that hasn't gotten a lot of attention lately. 

The primitives are what we use with the modeling functions. Most of our forward modeling in analytical and calculates the effects of a single primitive. So we needed a way of passing the object's dimensions and physical properties to the functions. Initially we used dicts but making a large list of dicts is not very efficient. But the primitive classes are still just basic containers.

**Comment by rowanc1** [comment]
Really cool. Can we set up a meeting (probably @lheagy + @leouieda + @rowanc1 + youtube) for this week to discuss a bit of a plan of attack?

**Comment by lheagy** [comment]
That would be great! I would appreciate hearing more about the current structure, where you see it going, and we can share some of the same. Is there a day that works best for you?

**Comment by leouieda** [comment]
That would be great! For me, Wednesdays are better or any other day in the evening. Might be a challenge with the timezones. Where are you both?

**Comment by rowanc1** [comment]
Calgary and Vancouver. I will hit you up on swung Slack.

**Comment by rowanc1** [comment]
@leouieda did you have any other thoughts on contributing any of this code to `discretize`? Things still need a lot of work over there. :) Also on docs/attribution as you noticed.

Would be totally awesome to start depending on some common geoscience packages. Let me know!

**Comment by leouieda** [comment]
@rowanc1 we've been running into some limitations of the way we currently deal with geometric objects in #370 by @birocoles. We were assuming that physical properties are independent of the geometry but that breaks down when you have things like self-demagnetization. So I've been giving `mesher` a bit of attention to modernize it a bit before pushing that into `discretize`. 

I confess that I need to play around with the library a bit more to get my head around the API. Your naming conventions confuse my PEP8 molded brain ;) But I really want access to the derivatives and mesh refinement. 

I've been thinking in terms of geometric objects with homogeneous physical properties for long that I'm having trouble getting out of that mindset. It's much easier to generalize when you're dealing only in meshes and numerical solutions. 

For example, the `TensorMesh` can be N-dimensional with the same code but that doesn't make sense for our `PrismMesh`, which is a collection of primitives. Maybe a nice way in would be to make some subclasses for these more specific types, e.g. `PrismMesh` can be a particular case of `TensorMesh` restricted to 3D. 

I'd love to hear your thoughts on this. Maybe we should move this discussion somewhere else?

> Would be totally awesome to start depending on some common geoscience packages. Let me know!

Yes it would!

**Comment by rowanc1** [comment]
First pass response complete here simpeg/discretize#40. Sorry for confusing your PEP8 brain. We will get up to fatiando standards eventually, bit of a bar you have set, PRs welcome. :)
