### ISSUE TITLE
Add copy method to classes in mesher

### ISSUE THREAD

**Issue by leouieda** [fatiando/fatiando#284]
Sometimes I'll need to make copies of `mesher` objects. It would be great to have a `.copy()` method in all classes.

**Comment by PiotrKurnik** [comment]
Hi @leouieda I will look into this. Basic question: do you think that returning constructor will be enough?

**Comment by leouieda** [comment]
@PiotrKurnik thanks! I'd really appreciate it.

The method should return a copy of the object, so not just the constructor. For example, if i want to modify the object but keep the original, i could call `old = my_obj.copy()`. This can be a wrapper for the `copy` module. 

Beware that you'd also gave to copy the objects `prop` attribute, which is a dictionary. Otherwise, changing the dict if one would also change the other.

**Comment by PiotrKurnik** [comment]
@leouieda thanks for reply!
I will try to follow your advice and use `copy.deepcopy`. That  would be my first open source contribution, so it will take time, still figuring out how stuff works :)

**Comment by leouieda** [comment]
No problem, take your time. Please keep me informed of your progress. You should open a pull request (PR) as soon as you have any code changes. You don't need to wait until you have finished. The PR is where we can discuss your contribution, I can what you are doing and help out. 

If you need help with git, opening the PR or anything else, we can chat on [gitter](https://gitter.im/fatiando/fatiando) or through the mailing list.
