### ISSUE TITLE
Old make cmds at Making a release in Developer guide

### ISSUE THREAD

**Issue by rafaelmds** [fatiando/fatiando#333]
Some options were removed in Makefile #280 (253d8ed8633755eef2d5bce76f9285b28a248f2d) like `make docs` and `make package`.

But the "Making a release" section in "Developer guide" was not updated and it still refers to this old commands.

Edit: I just found #302, so this issue is already covered anyway.

**Comment by leouieda** [comment]
@rafaelmds thanks for spotting this! That section has been very outdated for  a while and it's probably best to just get rid of it for now. The process changed a lot between v0.4 and now so it's in need of a rewrite (which will have to wait for #302).

For now, do you want to try to delete the "Making a release" section from the dev docs? It would be **greatly** appreciated! I can promise you a free Fatiando sticker shipped to you from the new batch I'm currently designing :smiley: 

The file you'll need to edit is [`doc/develop.rst` ](https://github.com/fatiando/fatiando/blob/master/doc/develop.rst). You can delete the whole section (that's the beauty of version control).

If you need any help getting started or working with git/github (branching, creating a pull request, etc), just let me know (either here or in the gitter chat).
