### ISSUE TITLE
AttributeError in gravmag_imaging_geninv.py

### ISSUE THREAD

**Issue by smallcaiyuan** [fatiando/fatiando#347]
operating system : windows 7

python version : 2.7 in Anaconda

fatiando v0.4

code that generated the error :   gravmag_imaging_geninv.py

command   python gravmag_imaging_geninv.py

Traceback (most recent call last):
  File "gravmag_imaging_geninv.py", line 30, in <module>
    0, 10000, 25)
  File "D:\Program Files\AnacondaInstall\lib\site-packages\fatiando\gravmag\imag
ing.py", line 232, in geninv
    freq, dataft = _getdataft(x, y, data, shape)
  File "D:\Program Files\AnacondaInstall\lib\site-packages\fatiando\gravmag\imag
ing.py", line 252, in _getdataft
    Fx, Fy = transform._getfreqs(x, y, data, shape)
AttributeError: 'module' object has no attribute '_getfreqs'

Thanks for help!

**Comment by leouieda** [comment]
@smallcaiyuan thanks for reporting this! It's probably a bug caused by our restructuring of the `gravmag.transform` module. This was not caught because the `gravmag.imaging` module is not covered by our tests and isn't included in the new Gallery.

I'll outline the fix below and tag this as a low hanging fruit in case anyone wants to have a go at fixing this (you're more than welcome to try and I'll help you with whatever you need).

**Comment by leouieda** [comment]
The fix would be to replace `transform._getfreqs(x, y, data, shape)` with `transform._fftfreqs(x, y, shape, shape)` in [line 252 of `fatiando/gravmag/imaging.py`](https://github.com/fatiando/fatiando/blob/master/fatiando/gravmag/imaging.py#L252). Then you can run the cookbook script again to check that it works. Please also check that the other recipes involving the imaging module work.

**Comment by leouieda** [comment]
@fatiando/contributors would anyone like to try to patch this? As soon as a fix is up we can make a small bugfix release (v0.5.1) to make this available.

**Comment by drandykass** [comment]
I could but it wouldn't be until January :(

**Comment by victortxa** [comment]
I can try doing this. Opening the Pull Request now.

**Comment by smallcaiyuan** [comment]
@leouieda  Thanks for your answers! 
The 4th parameter  of function transform._fftfreqs(x, y, shape, shape) is padshape. What should I provide for this paramter? Could you show me a simple example? Thank you!

def _fftfreqs(x, y, shape, padshape):
    """
    Get two 2D-arrays with the wave numbers in the x and y directions.
    """
    nx, ny = shape
    dx = (x.max() - x.min())/(nx - 1)
    fx = 2*numpy.pi*numpy.fft.fftfreq(padshape[0], dx)
    dy = (y.max() - y.min())/(ny - 1)
    fy = 2*numpy.pi*numpy.fft.fftfreq(padshape[1], dy)
    return numpy.meshgrid(fy, fx)[::-1]

**Comment by leouieda** [comment]
@smallcaiyuan sorry but @victortxa already patched this yesterday (he was very fast!) in #348. You can have a look there to see what was changed (see the "Files changed"  tab).

The `padshape`  is there to allow the use of padding for the grids before FFT. If there is no padding, as was this case, we just pass in the `shape` argument again.

**Comment by leouieda** [comment]
If you don't want to wait for the next release to get this fix, you can use the development version of Fatiando. It's perfectly safe to use because we only merge in changes that pass all our tests. See the instructions here: http://www.fatiando.org/install.html#installing-the-latest-development-version

**Comment by smallcaiyuan** [comment]
@leouieda and @victortxa
I made the change according to victortxa's patching method in #348, and the problem is solved!
Thanks for your help!





At 2016-12-02 19:13:58, "Leonardo Uieda" <notifications@github.com> wrote:


@smallcaiyuan sorry but @victortxa already patched this yesterday (he was very fast!) in #348. You can have a look there to see what was changed (see the "Files changed" tab).

The padshape is there to allow the use of padding for the grids before FFT. If there is no padding, as was this case, we just pass in the shape argument again.

**Comment by leouieda** [comment]
@smallcaiyuan OK, good to know that things are working now!

**Comment by smallcaiyuan** [comment]
Thank you!







At 2016-12-05 20:08:41, "Leonardo Uieda" <notifications@github.com> wrote:


@smallcaiyuan OK, good to know that things are working now!
