### ISSUE TITLE
Add gallery plot for radial average power spectrum

### ISSUE THREAD

**Issue by leouieda** [fatiando/fatiando#356]
We need a gallery plot for the code implemented in #303. Can use the new Hawaii gravity data from #355.

**Comment by leouieda** [comment]
@santis19 would you like to take a shot at this?

**Comment by santis19** [comment]
Hi @leouieda. I can get this done by next week if that's ok for you.

**Comment by leouieda** [comment]
There's no hurry, whenever you can do this is fine. It's all volunteer time :smile:
