### ISSUE TITLE
Missing functions on mpl.py

### ISSUE THREAD

**Issue by ffigura** [fatiando/fatiando#399]
python 2.7.12 64 bits, Qt 4.8.7, PyQt4 Spyder 2.3.8 windows 10

version_version = 'b1abf5e2f1b444cfd5251627710510372e27c33a'
version_full = 'b1abf5e2f1b444cfd5251627710510372e27c33a'

I tried to run http://www.fatiando.org/cookbook/gravmag_mag_prism.html and got error messages because the following functions are missing on mpl.py:

mpl.figure()
mpl.title()
mpl.axis()
mpl.colorbar()
mpl.xlabel()
mpl.ylabel()
mpl.show()

**Comment by victortxa** [comment]
@ffigura try this:
```
from fatiando import mesher, gridder, utils
from fatiando.gravmag import prism
from fatiando.vis import mpl, myv
import matplotlib.pyplot as plt

[rest of the code]

plt.figure()
plt.title("Total-field anomaly (nT)")
plt.axis('scaled')
mpl.contourf(yp, xp, tf, shape, 15)
plt.colorbar()
plt.xlabel('East y (km)')
plt.ylabel('North x (km)')
mpl.m2km()
plt.show()
```

**Comment by victortxa** [comment]
Is `myavi` working for you? My problem is with the `myavi` original package

**Comment by ffigura** [comment]
Hey @victortxa, thanks for the reply. I did this workaround when I faced the issue, I reported because something need to be changed: the example in the cookbook or add the function in the library mpl.py. From my point of view these functions should be added to the lirbrary in order to keep everything on mpl. style.
Myavi worked fine in this verison

**Comment by victortxa** [comment]
I think it's because this module will be removed in the version 0.6. But, it is true it can be confusing.

**Comment by leouieda** [comment]
@ffigura Do you get errors or warnings? 

These functions are the same ones from matplotlib.pyplot so you should use that instead. We're removing support for vis.mpl in the near future. The cookbook is also very outdated and will also be removed in favor of the new Gallery (here is a preview http://www.fatiando.org/dev/gallery/).

**Comment by ffigura** [comment]
@leouieda as I said the error messages are because the example at the cookbook calls the functions on mpl.py that I listed but this functions are not on that library. The workaround I did was the same as Victor suggested, call directly from matplotlib.

**Comment by leouieda** [comment]
@ffigura I just noticed that you're using the latest development version of Fatiando. Those functions were removed and the whole module will be reworked before v0.6. If you're using the development version, then also use the development version of the docs: http://www.fatiando.org/dev/

Otherwise you'll get these kinds of errors because we changed something in *master*.

**Comment by ffigura** [comment]
Great, thanks for the clarification @leouieda! I was worried that something would be missing in a new version, this happens often.
