### ISSUE TITLE
Problem with mayavi

### ISSUE THREAD

**Issue by leobvital** [fatiando/fatiando#403]
Hi, Leo!

I have a problem to run mayavi on my computer. I've tried to run the cookbook from fatiando and the error still the same.

# **My OS is:**
Ubuntu MATE 1.12.1
Kernel Linux 4.4.0-78-generic x86_64
Release 16.04.1 LTS (Xenial Xerus) 64-bit
Python 2.7.13
fatiando 0.5

I've installed anaconda for python 2.7. After, I've installed fatiando and mayavi using the codes:

conda install fatiando --channel conda-forge

conda install fatiando mayavi --channel conda-forge

# **The code is:**

"""
Vis: Set the colors in figures, prisms, polygonal prisms and tesseroids.
"""
from fatiando.mesher import Prism, PolygonalPrism, Tesseroid
from fatiando.vis import myv

prism = Prism(1, 2, 1, 2, 0, 1, {'density': 1})
polyprism = PolygonalPrism([[3, 1], [4, 2], [5, 1]], -1, 2, {'density': 2})
tesseroid = Tesseroid(10, 20, 50, 60, 10 ** 6, 0)

red, green, blue = (1, 0, 0), (0, 1, 0), (0, 0, 1)
white, black = (1, 1, 1), (0, 0, 0),

myv.figure()
% Make the prism red with blue edges, despite its density
myv.prisms([prism], 'density', color=red, edgecolor=blue)
% and the polyprism green with blue edges
myv.title('Body + edge colors')

myv.figure()
% For wireframes, color is usually set by the density.
# Overwrite this by setting *color*
% *edgecolor* is ignored
myv.polyprisms([polyprism], 'density', style='wireframe', color=green,
               edgecolor=red, linewidth=2)
myv.title('Wireframe colors')

% Black background, white lines, green tesseroid
myv.figure(zdown=False, color=black)
myv.earth()
myv.continents(color=white)
myv.tesseroids([tesseroid], color=green, edgecolor=white)
myv.title('Black background', color=white)
myv.show()

# **The error is:**

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-716eea4f6c84> in <module>()
----> 1 myv.figure()
      2 # Make the prism red with blue edges, despite its density
      3 myv.prisms([prism], 'density', color=red, edgecolor=blue)
      4 # and the polyprism green with blue edges
      5 myv.title('Body + edge colors')

/home/vital/anaconda2/lib/python2.7/site-packages/fatiando/vis/myv.pyc in figure(size, zdown, color)
    617     _lazy_import_mlab()
    618     if size is None:
--> 619         fig = mlab.figure(bgcolor=color)
    620     else:
    621         fig = mlab.figure(bgcolor=color, size=size)

/home/vital/anaconda2/lib/python2.7/site-packages/mayavi/tools/figure.pyc in figure(figure, bgcolor, fgcolor, engine, size)
     61     else:
     62         if engine is None:
---> 63             engine = get_engine()
     64         if figure is None:
     65             name = max(__scene_number_list) + 1

/home/vital/anaconda2/lib/python2.7/site-packages/mayavi/tools/engine_manager.pyc in get_engine(self)
     99                                 if e.__class__.__name__ == 'Engine']
    100         if len(suitable) == 0:
--> 101             return self.new_engine()
    102         else:
    103             # Return the most engine add to the list most recently.

/home/vital/anaconda2/lib/python2.7/site-packages/mayavi/tools/engine_manager.pyc in new_engine(self)
    144             options.
    145         """
--> 146         check_backend()
    147         if options.backend == 'envisage':
    148             from mayavi.plugins.app import Mayavi

/home/vital/anaconda2/lib/python2.7/site-packages/mayavi/tools/engine_manager.pyc in check_backend()
     47 wxPython: http://www.wxpython.org/
     48 PyQT: http://www.riverbankcomputing.co.uk/software/pyqt/intro
---> 49 ''')
     50 
     51 

ImportError: Could not import backend for traits
_______________________________________________________________________________
Make sure that you have either the TraitsBackendWx or the TraitsBackendQt
projects installed. If you installed Mayavi with easy_install, try
easy_install <pkg_name>. easy_install Mayavi[app] will also work.

If you performed a source checkout, be sure to run 'python setup.py install'
in Traits, TraitsGUI, and the Traits backend of your choice.

Also make sure that either wxPython or PyQT is installed.
wxPython: http://www.wxpython.org/
PyQT: http://www.riverbankcomputing.co.uk/software/pyqt/intro

I've tried to install that two packages wxPython and PyQT and run the code again, so the kernel on jupyter notebook died.

**Comment by leouieda** [comment]
@leobvital oh great, another new Mayavi related error :)

Thanks for reporting. I'll try to reproduce this here. What are you trying to plot?

For the moment, please try uninstalling everything (maybe even delete your `anaconda2` folder) and reinstalling. That sometimes fixes whatever problem this might be.

You don't need to run `conda install` twice. If you want to use Fatiando with Mayavi just use the second one. 

Also, please avoid the cookbook recipes because they aren't being maintained or updated. They will probably all be removed in the next release (replaced by the Gallery).

**Comment by leobvital** [comment]
@leouieda I'm trying to plot polyprisms for my project. I wanna compare true and calculated geometric parameters after inversion.

I've deleted anaconda2 folder and reinstalled, but the error still the same.

The same error occurs in my code without using cookbook.

**Comment by leouieda** [comment]
@leobvital after much googling, I managed to get my Mayavi working by:

1. Add `export ETS_TOOLKIT=qt4` to your `.bashrc` file in your home folder. Restart the terminal.
2. Install pyside: `conda install pyside -c conda-forge`

See if this works for you.

**Comment by leobvital** [comment]
IT WORKS!

Thank you, @leouieda!

**Comment by leouieda** [comment]
Great!
