### ISSUE TITLE
Verify datasets downloaded by `fatiando.datasets` using a recorded hash

### ISSUE THREAD

**Issue by leouieda** [fatiando/fatiando#47]
The idea is to implement a [decorator](http://simeonfranklin.com/blog/2012/jul/1/python-decorators-in-12-steps/) that verifies the data using a recorded hash (md5, sha, etc) of the dataset that lives as a string in the module.

Computing the hash might be a bit slow so this can be an optional thing. Also, it can be done when the data is downloaded. Then an extra function could be added that verifies a given filename so that the validation can be done on load.

The idea came from this talk by @ivanov: http://www.youtube.com/watch?feature=player_embedded&v=Nj_8lwMKD_g

He talks about it around minute 12.

**Comment by leouieda** [comment]
Ended up implementing a function for this instead. It's called from the data loading functions.

**Comment by ivanov** [comment]
woo! 👍
